apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: service-mesh-demo
  labels:
    app: orders
    service: orders
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: orders
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-mesh-demo-orders
  namespace: service-mesh-demo
  labels:
    account: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: service-mesh-demo
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: orders
    spec:
      serviceAccountName: service-mesh-demo-orders
      containers:
      - name: orders
        image: registry.ocp4.imss.com:8443/ocp4/openshift4-service-mesh-orders
        imagePullPolicy: IfNotPresent
        env:
        - name: PAYMENTS_URL
          value: "http://payments:8080"
        - name: RECOMMENDATIONS_URL
          value: "http://recommendations:8080"
        ports:
        - containerPort: 8080   
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: orders
  namespace: service-mesh-demo
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: orders
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
